### ISSUE TITLE
Initialise Node Server

### ISSUE THREAD

**Issue by JeyzerMC** [HackMerced/HackMerced#2]
Setup the NodeJS server with ExpressJS

- [x] Create the server
- [x] Add Express to it
- [x] Test the server

**Comment by dragonbone81** [comment]
any specific endpoints, that do any specific thing?

**Comment by dragonbone81** [comment]
the node server should be good. at least the basic stuff @JeyzerMC

**Comment by JeyzerMC** [comment]
Good job! 
In the future though, please submit Pull Requests from a branch instead of pushing directly to master, so we can review it before merging. Also consider forking the repository for that reason. @dragonbone81
