### ISSUE TITLE
Get User Info

### ISSUE THREAD

**Issue by JeyzerMC** [HackMerced/HackMerced#47]
Checking service for the validation at door

- [x] Check if the e-mail is in the DB
- [x] Check hacker status
- [x] Retrieve shirt size info, role and registration status for said hacker

Basically making a small web page that can do that. You enter the name or email of the hacker (or scan their QR code if we do one) and it will give you back information so you can give them their starter pack and let them in.

**Comment by dragonbone81** [comment]
This does nothing.
This is just retreiving user info by email. This is not check-in
We already have this route. Can just add a permission that checks if user is admin or whatever role you want to give for this action. 
@adriandarian @JeyzerMC

**Comment by dragonbone81** [comment]
Rename to just getUserInfo
