### ISSUE TITLE
UI Page for Sponsor Us on Hub

### ISSUE THREAD

**Issue by shiv248** [HackMerced/HackMerced#78]
* Sponsors can go to this page and have a form to fill in name, company, email, and message if they want to sponsor us and like our hackathon

- [ ] name

- [ ] company

- [ ] email

- [ ] message

if possible, put a character count on the message

**Comment by shiv248** [comment]
@maryharebear please edit my issue and add your UI criterias.

**Comment by maryharebear** [comment]
@shiv248 that's it, only one form @ asana I referenced calhacks sponsor us page, that's how simple I want it to be. Do not copy the words they have on calhacks e.g. "Make Cal Hacks your event" and their text. I just need one form. Thanks!

**Comment by adriandarian** [comment]
Closing because this issue was already referenced on our Asana.
